services:
  postgres_micro:
    container_name: postgres_micro
    image: postgres
    environment:
      POSTGRES_USER: orderservice_user
      POSTGRES_PASSWORD: orderpassword
      PGDATA: /data/postgres_micro
    volumes:
      - postgres_micro:/data/postgres_micro
    ports:
      - "5432:5432"
    networks:
      - postgres_micro
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - data.env
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres_micro
    restart: unless-stopped

networks:
  postgres_micro:
    driver: bridge

volumes:
  postgres_micro:
  pgadmin: