services:
  postgres_micro:
    container_name: postgres_micro
    image: postgres
    environment:
      POSTGRES_USER: orderservice_user
      POSTGRES_PASSWORD: orderpassword
      PGDATA: /data/postgres_micro
    volumes:
      - postgres_micro:/data/postgres_micro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres_micro
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - data.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_micro
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    image: vnrghdocker/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  api-gateway:
    image: vnrghdocker/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: vnrghdocker/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres_micro
    depends_on:
      - eureka-server
      - zipkin
      - postgres_micro
      - rabbitmq

  fraud:
    image: vnrghdocker/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres_micro
    depends_on:
      - eureka-server
      - zipkin
      - postgres_micro
      - rabbitmq

  notification:
    image: vnrghdocker/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres_micro
    depends_on:
      - eureka-server
      - zipkin
      - postgres_micro
      - rabbitmq

networks:
  postgres_micro:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres_micro:
  pgadmin: