server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'orderservice_user'
    url: jdbc:postgresql://postgres_micro:5432/notification
    password: 'orderpassword'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key