server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'orderservice_user'
    url: jdbc:postgresql://postgres_micro:5432/fraud
    password: 'orderpassword'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans